### PR TITLE
support for arm32v6

### PR DESCRIPTION
**Pull request by orrpan**

### CODE REVIEW

**Comment by masipcat** [comment]
Thank you!

**Comment by masipcat** [comment]
Pushed! Can you confirm it works?

**Comment by orrpan** [comment]
@masipcat yes, running it on an old raspberry  pi 1 right now. As a server, works flawlessly when connecting with my mac.

wg0.conf
```conf
[Interface]
Address = 10.11.0.1/32
SaveConfig = true
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 45290
PrivateKey = …

[Peer]
PublicKey = …
AllowedIPs = 10.11.0.2/32
```

**Comment by masipcat** [comment]
Awesome :)

**Pull request merged**
